### ISSUE TITLE
Building with newer frameworks?

### ISSUE THREAD

**Issue by brody2consult** [mschulkind/cordova-true-native-android#4]
Hi @mschulkind,

I finally had a chance to try your project. I figured out how to initialize the Git submodule, ended up removing a few Cordova modules that were using Base64, but am having trouble finding/building/installing the right version of Spider Monkey for this project. I ended up building and running based on commit dc41d2c (right before the Spider Monkey changes). I ended up with a screen with 3 empty green bars, which is a first sign of life for me.

Considering that both Android and iOS would have newer Javascript engines built-in, I really do not feel like struggling with Spider Monkey. My idea is to port and build one class or window at a time within the newer Cordova 3.x/4.x framework, starting with the TableView in main.coffee.

Also, I tried running the example in the iOS project (without Spider Monkey) and get the web view with the spinner. The console gives me the `Message: Can't find variable: cordova` and points to the source/offending line: `1: cordova.fireDocumentEvent('active');`

For the iOS version, I am also thinking to port and build one control/view/window at a time to Cordova 3.x/4.x.

Does this sound like a good approach and can you think of any quick suggestions?

If I get either or both Android and iOS versions working with Cordova 3.x/4.x (without embedded SpiderMonkey) I am happy to start issuing pull requests.

Thanks,
Chris

**Comment by mschulkind** [comment]
What do you mean about the Base64 stuff? Maybe that's related to the missing cordova? Base64 stuff is involved in how it loads the JS it needs:
https://github.com/mschulkind/cordova-true-native-ios#baked-in-javascript

Seems fine to remove spidermonkey if it's not needed anymore, but it may still be faster with it, and it's likely simpler since last I used both iOS and Android, there was no way to directly poke at JS objects from the native side with the built in javascript engines.

Also, even though it looks like it's iOS only right now, don't miss [React Native](https://facebook.github.io/react-native/).

**Comment by brody2consult** [comment]
Thanks @mschulkind. I was able to solve the issue with the Base64 stuff.

I was able to get the first list/table view constructed, by passing some child/children options when constructing the parent. Convoluted, but it worked. I am happy to post a pull sometime if anyone wants it.

And I was able to build on Cordova 2.6 with a few minor changes.

Yes I did already see React Native. Also found https://github.com/photokandyStudios/PKNativeControls for iOS (FWIW).

I will let you know if I do anything else with this project. Thanks again for sharing such a nice project-I wish I had seen it 2-3 years ago!
